compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: false

enableHardenedMode: false

nodeLinker: node-modules

plugins:
  - checksum: b023a66bd5b071f92c561b1a3815c12f462f00ec92647f54d7ad88ae81c35cb4f25e70b6664112edcf33fef17b7b4daf55a2fd7a2abe57b7699c1805d9116f43
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: "https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v1.0.3/bundles/@yarnpkg/plugin-nolyfill.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.4.cjs
