// List of languages in FLORES-200 is available here:
// https://github.com/facebookresearch/flores/blob/main/flores200/README.md#languages-in-flores-200

export interface Language {
    label: string
    value: string
    code: string
}

export const LANGUAGES: Language[] = [
    { label: "Afrikaans", value: "afr_Latn", code: "af" },
    { label: "Akan", value: "aka_Latn", code: "ak" },
    { label: "Amharic", value: "amh_Ethi", code: "am" },
    { label: "Armenian", value: "hye_Armn", code: "hy" },
    { label: "Assamese", value: "asm_Beng", code: "as" },
    { label: "Bambara", value: "bam_Latn", code: "bm" },
    { label: "Bashkir", value: "bak_Cyrl", code: "ba" },
    { label: "Basque", value: "eus_Latn", code: "eu" },
    { label: "Belarusian", value: "bel_Cyrl", code: "be" },
    { label: "Bengali", value: "ben_Beng", code: "bn" },
    { label: "Bosnian", value: "bos_Latn", code: "bs" },
    { label: "Bulgarian", value: "bul_Cyrl", code: "bg" },
    { label: "Burmese", value: "mya_Mymr", code: "my" },
    { label: "Catalan", value: "cat_Latn", code: "ca" },
    { label: "Central Aymara", value: "ayr_Latn", code: "ay" },
    { label: "Chinese (Simplified)", value: "zho_Hans", code: "zh" },
    { label: "Chinese (Traditional)", value: "zho_Hant", code: "zh" },
    { label: "Croatian", value: "hrv_Latn", code: "hr" },
    { label: "Czech", value: "ces_Latn", code: "cs" },
    { label: "Danish", value: "dan_Latn", code: "da" },
    { label: "Dutch", value: "nld_Latn", code: "nl" },
    { label: "Dzongkha", value: "dzo_Tibt", code: "dz" },
    { label: "Eastern Panjabi", value: "pan_Guru", code: "pa" },
    { label: "Eastern Yiddish", value: "ydd_Hebr", code: "yi" },
    { label: "English", value: "eng_Latn", code: "en" },
    { label: "Esperanto", value: "epo_Latn", code: "eo" },
    { label: "Estonian", value: "est_Latn", code: "et" },
    { label: "Ewe", value: "ewe_Latn", code: "ee" },
    { label: "Faroese", value: "fao_Latn", code: "fo" },
    { label: "Fijian", value: "fij_Latn", code: "fj" },
    { label: "Finnish", value: "fin_Latn", code: "fi" },
    { label: "Fon", value: "fon_Latn", code: "fon" },
    { label: "French", value: "fra_Latn", code: "fr" },
    { label: "Galician", value: "glg_Latn", code: "gl" },
    { label: "Ganda", value: "lug_Latn", code: "lg" },
    { label: "Georgian", value: "kat_Geor", code: "ka" },
    { label: "German", value: "deu_Latn", code: "de" },
    { label: "Greek", value: "ell_Grek", code: "el" },
    { label: "Guarani", value: "grn_Latn", code: "gn" },
    { label: "Gujarati", value: "guj_Gujr", code: "gu" },
    { label: "Haitian Creole", value: "hat_Latn", code: "ht" },
    { label: "Halh Mongolian", value: "khk_Cyrl", code: "mn" },
    { label: "Hausa", value: "hau_Latn", code: "ha" },
    { label: "Hebrew", value: "heb_Hebr", code: "he" },
    { label: "Hindi", value: "hin_Deva", code: "hi" },
    { label: "Hungarian", value: "hun_Latn", code: "hu" },
    { label: "Icelandic", value: "isl_Latn", code: "is" },
    { label: "Igbo", value: "ibo_Latn", code: "ig" },
    { label: "Indonesian", value: "ind_Latn", code: "id" },
    { label: "Irish", value: "gle_Latn", code: "ga" },
    { label: "Italian", value: "ita_Latn", code: "it" },
    { label: "Japanese", value: "jpn_Jpan", code: "ja" },
    { label: "Javanese", value: "jav_Latn", code: "jv" },
    { label: "Kannada", value: "kan_Knda", code: "kn" },
    { label: "Kashmiri (Arabic script)", value: "kas_Arab", code: "ks" },
    { label: "Kashmiri (Devanagari script)", value: "kas_Deva", code: "ks" },
    { label: "Kazakh", value: "kaz_Cyrl", code: "kk" },
    { label: "Khmer", value: "khm_Khmr", code: "km" },
    { label: "Kikongo", value: "kon_Latn", code: "kg" },
    { label: "Kikuyu", value: "kik_Latn", code: "ki" },
    { label: "Kinyarwanda", value: "kin_Latn", code: "rw" },
    { label: "Korean", value: "kor_Hang", code: "ko" },
    { label: "Kyrgyz", value: "kir_Cyrl", code: "ky" },
    { label: "Lao", value: "lao_Laoo", code: "lo" },
    { label: "Latgalian", value: "ltg_Latn", code: "ltg" },
    { label: "Ligurian", value: "lij_Latn", code: "lij" },
    { label: "Limburgish", value: "lim_Latn", code: "li" },
    { label: "Lingala", value: "lin_Latn", code: "ln" },
    { label: "Lithuanian", value: "lit_Latn", code: "lt" },
    { label: "Luo", value: "luo_Latn", code: "luo" },
    { label: "Luxembourgish", value: "ltz_Latn", code: "lb" },
    { label: "Macedonian", value: "mkd_Cyrl", code: "mk" },
    { label: "Magahi", value: "mag_Deva", code: "mag" },
    { label: "Maithili", value: "mai_Deva", code: "mai" },
    { label: "Malayalam", value: "mal_Mlym", code: "ml" },
    { label: "Maltese", value: "mlt_Latn", code: "mt" },
    { label: "Maori", value: "mri_Latn", code: "mi" },
    { label: "Marathi", value: "mar_Deva", code: "mr" },
    { label: "Mizo", value: "lus_Latn", code: "lus" },
    { label: "Modern Standard Arabic (Romanized)", value: "arb_Latn", code: "ar" },
    { label: "Modern Standard Arabic", value: "arb_Arab", code: "ar" },
    { label: "Moroccan Arabic", value: "ary_Arab", code: "ary" },
    { label: "Nepali", value: "npi_Deva", code: "ne" },
    { label: "North Azerbaijani", value: "azj_Latn", code: "az" },
    { label: "Northern Sotho", value: "nso_Latn", code: "nso" },
    { label: "Northern Uzbek", value: "uzn_Latn", code: "uz" },
    { label: "Norwegian Bokmål", value: "nob_Latn", code: "nb" },
    { label: "Norwegian Nynorsk", value: "nno_Latn", code: "nn" },
    { label: "Nuer", value: "nus_Latn", code: "nus" },
    { label: "Nyanja", value: "nya_Latn", code: "ny" },
    { label: "Occitan", value: "oci_Latn", code: "oc" },
    { label: "Odia", value: "ory_Orya", code: "or" },
    { label: "Plateau Malagasy", value: "plt_Latn", code: "mg" },
    { label: "Polish", value: "pol_Latn", code: "pl" },
    { label: "Portuguese", value: "por_Latn", code: "pt" },
    { label: "Romanian", value: "ron_Latn", code: "ro" },
    { label: "Rundi", value: "run_Latn", code: "rn" },
    { label: "Russian", value: "rus_Cyrl", code: "ru" },
    { label: "Samoan", value: "smo_Latn", code: "sm" },
    { label: "Sango", value: "sag_Latn", code: "sg" },
    { label: "Sanskrit", value: "san_Deva", code: "sa" },
    { label: "Sardinian", value: "srd_Latn", code: "sc" },
    { label: "Scottish Gaelic", value: "gla_Latn", code: "gd" },
    { label: "Serbian", value: "srp_Cyrl", code: "sr" },
    { label: "Shan", value: "shn_Mymr", code: "shn" },
    { label: "Shona", value: "sna_Latn", code: "sn" },
    { label: "Sindhi", value: "snd_Arab", code: "sd" },
    { label: "Sinhala", value: "sin_Sinh", code: "si" },
    { label: "Slovak", value: "slk_Latn", code: "sk" },
    { label: "Slovenian", value: "slv_Latn", code: "sl" },
    { label: "Somali", value: "som_Latn", code: "so" },
    { label: "Southern Pashto", value: "pbt_Arab", code: "ps" },
    { label: "Southern Sotho", value: "sot_Latn", code: "st" },
    { label: "Spanish", value: "spa_Latn", code: "es" },
    { label: "Standard Latvian", value: "lvs_Latn", code: "lv" },
    { label: "Standard Malay", value: "zsm_Latn", code: "ms" },
    { label: "Standard Tibetan", value: "bod_Tibt", code: "bo" },
    { label: "Sundanese", value: "sun_Latn", code: "su" },
    { label: "Swahili", value: "swh_Latn", code: "sw" },
    { label: "Swati", value: "ssw_Latn", code: "ss" },
    { label: "Swedish", value: "swe_Latn", code: "sv" },
    { label: "Tagalog", value: "tgl_Latn", code: "tl" },
    { label: "Tajik", value: "tgk_Cyrl", code: "tg" },
    { label: "Tamil", value: "tam_Taml", code: "ta" },
    { label: "Tatar", value: "tat_Cyrl", code: "tt" },
    { label: "Telugu", value: "tel_Telu", code: "te" },
    { label: "Thai", value: "tha_Thai", code: "th" },
    { label: "Tigrinya", value: "tir_Ethi", code: "ti" },
    { label: "Tok Pisin", value: "tpi_Latn", code: "tpi" },
    { label: "Tosk Albanian", value: "als_Latn", code: "sq" },
    { label: "Tsonga", value: "tso_Latn", code: "ts" },
    { label: "Tswana", value: "tsn_Latn", code: "tn" },
    { label: "Tumbuka", value: "tum_Latn", code: "tum" },
    { label: "Turkish", value: "tur_Latn", code: "tr" },
    { label: "Turkmen", value: "tuk_Latn", code: "tk" },
    { label: "Twi", value: "twi_Latn", code: "tw" },
    { label: "Ukrainian", value: "ukr_Cyrl", code: "uk" },
    { label: "Urdu", value: "urd_Arab", code: "ur" },
    { label: "Uyghur", value: "uig_Arab", code: "ug" },
    { label: "Vietnamese", value: "vie_Latn", code: "vi" },
    { label: "Welsh", value: "cym_Latn", code: "cy" },
    { label: "West Central Oromo", value: "gaz_Latn", code: "om" },
    { label: "Western Persian", value: "pes_Arab", code: "fa" },
    { label: "Wolof", value: "wol_Latn", code: "wo" },
    { label: "Xhosa", value: "xho_Latn", code: "xh" },
    { label: "Yoruba", value: "yor_Latn", code: "yo" },
    { label: "Yue Chinese", value: "yue_Hant", code: "yue" },
    { label: "Zulu", value: "zul_Latn", code: "zu" },
]
