// Generated by Wrangler on Mon May 20 2024 11:59:44 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
	PLUGIN_URI: string;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
}
