// Generated by Wrangler on Sat May 25 2024 13:13:40 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	keyValueStore: KVNamespace;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
	PLUGIN_URI: string;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
}
