export { default as AccountPage } from "./Account"
export { default as ChatPage } from "./Chat"
export { default as FormsPage } from "./forms"
export { default as FormsInstallationPage } from "./forms/installation"
export { default as MeetingsPage } from "./Meetings"
export { default as CanvasMenuPage } from "./Menu"
export { default as TrackingPage } from "./tracking"
export { default as LearnMoreTrackingPage } from "./tracking/learn-more"
